import { StyleSheet } from "react-native";
import { FOOTER_COLOUR } from "./main";

export const buttonStyles = StyleSheet.create({
  button: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    backgroundColor: "green",
  },
  next: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: "skyblue",
    alignSelf: "flex-end",
    marginHorizontal: "1%",
    marginBottom: 6,
    minWidth: "48%",
    textAlign: "center",
  },
  prev: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: "skyblue",
    alignSelf: "flex-start",
    marginHorizontal: "1%",
    marginBottom: 6,
    minWidth: "48%",
    textAlign: "center",
  },
  show: {
    //display: "flex",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: "skyblue",
    //alignSelf: "flex-start",
    marginHorizontal: "1%",
    marginBottom: 6,
    minWidth: "48%",
    textAlign: "center",
  },
  hide: {
    //display: "none",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: FOOTER_COLOUR,
    //alignSelf: "flex-start",
    marginHorizontal: "1%",
    marginBottom: 6,
    minWidth: "48%",
    textAlign: "center",
  },
  navButtonLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "black",
    textAlign: "center",
    textAlignVertical: "center",
  },
  navButtonLabelHidden: {
    fontSize: 12,
    fontWeight: "500",
    color: FOOTER_COLOUR,
  },
  text: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
  answerButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: "oldlace",
    alignSelf: "flex-start",
    marginHorizontal: "1%",
    marginBottom: 6,
    minWidth: "48%",
    textAlign: "center",
  },
  answerButtonLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: "coral",
  },
  newNavButton: {
    //display: "block",
    minWidth: 50,
    alignItems: "center",
    textAlignVertical: "center",
    backgroundColor: "whitesmoke",
    borderRadius: 70,
    borderColor: "gainsboro",
    borderWidth: 3,
    height: 70,
    justifyContent: "center",
  },
  newNavButtonLabel: {
    fontSize: 20,
    fontWeight: "bold",
    color: "gainsboro",
    textAlign: "center",
    textAlignVertical: "center",
  },
});
